### PR TITLE
Promote efac3571027646b8755b0feb43fffbfaf1aa7672 to prod.

### PR DESCRIPTION
**Pull request by twiest**

### CODE REVIEW

**Review by jmelis — APPROVED** [review]

**Comment by jmelis** [comment]
we have seen that after merging to master there have been succesful deployments

**Comment by twiest** [comment]
@jmelis going to wait on this as @joelddiaz has a PR incoming that we want to push to prod as well.

**Comment by twiest** [comment]
@jmelis hey, I think this code is ready to go to prod. Can I get a +1 please?

It passed the UHC STG e2e test:

```
Success > Console Output#1​98 Apr 23, 2019 6:00 AM
```

**Comment by jmelis** [comment]
+1 to merge, thanks @twiest

**Pull request merged**
