### PR TITLE
SREP-1294: Promote to prod

### PR DESCRIPTION
**Pull request by lisa**
Let's see if openshift/configure-alertmanager-operator@20f4550bc6f2c56dfd91bca5dc267696a45f6a28

See #37 and #36

### CODE REVIEW

**Comment by jfchevrette** [comment]
> error: unknown parameter name "ADDITIONAL_CERTIFICATE_AUTHORITY"

Parameter is defined in `hive-services/hive.yaml` but is not present in the template that is in the upstream repo at the corresponding commit hash (it is in master though)

**Comment by jfchevrette** [comment]
Blocked by https://github.com/openshift/hive/pull/399

**Comment by rogbas** [comment]
@lisa @dak1n1 merged some commits after this hash, should we update to the most recent one

**Comment by lisa** [comment]
@rogbas Updated to `20f4550bc6f2c56dfd91bca5dc267696a45f6a28`. I think `2b567063614800df4bfd4f1000f4ab50bde22621` (most recent) will cause issues (see https://github.com/openshift/configure-alertmanager-operator/pull/33#pullrequestreview-241189786)

**Comment by jfchevrette** [comment]
I have a fix in flight for `Error: unknown flag: --dry-run` on the `configure-alertmanager-operator` check

**Comment by jfchevrette** [comment]
[test]

**Comment by jfchevrette** [comment]
https://github.com/openshift/hive/pull/399 is merged.

Now in order for this PR checks to pass we'll need to bump the hash in `hive-services/hive.yaml`. I think it's preferable if this happens in a different PR and then rebase this one once it is merged. WDYT?

**Comment by lisa** [comment]
> [openshift/hive#399](https://github.com/openshift/hive/pull/399) is merged.
> 
> Now in order for this PR checks to pass we'll need to bump the hash in `hive-services/hive.yaml`. I think it's preferable if this happens in a different PR and then rebase this one once it is merged. WDYT?

No complaints here.

**Comment by jewzaam** [comment]
PR needs rebase and then tests should pass.

**Comment by jewzaam** [comment]
LGTM

**Review by jfchevrette — APPROVED** [review]

**Pull request merged**
